# Generated by Django 5.0.6 on 2024-06-12 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogging_app", "0003_remove_comment_likes_alter_user_phone_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                related_query_name="like",
                to="blogging_app.post",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                related_query_name="like",
                to="blogging_app.user",
            ),
        ),
    ]
