# Generated by Django 5.0.6 on 2024-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogging_app", "0004_alter_like_post_alter_like_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Post Category",
                "verbose_name_plural": "Post Categories",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=500),
        ),
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(
                related_name="posts",
                related_query_name="post",
                to="blogging_app.postcategory",
            ),
        ),
    ]
