# Generated by Django 5.0.6 on 2024-06-14 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lib_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="lib_management.profile",
            ),
        ),
    ]
