# Generated by Django 5.0.6 on 2024-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lib_management", "0002_alter_address_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookrecord",
            name="category",
            field=models.CharField(
                choices=[
                    ("Fiction", "Fiction"),
                    ("Horror", "Horror"),
                    ("Sci-fi", "Sci-fi"),
                    ("Thriller", "Thriller"),
                    ("Children", "Children"),
                    ("Mystery", "Mystery"),
                ],
                default="Fiction",
                max_length=40,
            ),
        ),
    ]
