# Generated by Django 5.0.6 on 2024-06-06 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0004_productcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
