# Generated by Django 5.0.6 on 2024-06-06 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0005_remove_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
    ]
