# Generated by Django 5.0.6 on 2024-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0007_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Category",
            field=models.ManyToManyField(to="Inventory.category"),
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
