# Generated by Django 5.0.6 on 2024-06-06 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0008_product_category_delete_productcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Category",
            new_name="category",
        ),
    ]
